**Perform various operations on array using numpy library**

In [1]:
import numpy as np

In [2]:
A = [10, 20, 30]
B = [2, 3, 5]
arr1 = np.array(A)
arr2 = np.array(B)

In [3]:
print(arr1+arr2)

[12 23 35]


In [4]:
print(arr1/arr2)

[5.         6.66666667 6.        ]


In [5]:
print(arr1/5)

[2. 4. 6.]


In [6]:
print(arr1.dtype)

int64


In [7]:
print(type(arr2))

<class 'numpy.ndarray'>


In [8]:
print(arr1.ndim)

1


In [9]:
A=[1,2,3]
B=[4,5,6]
arr3=np.array([A,B])

In [10]:
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [12]:
arr4=np.arange(10)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr5=np.arange(1,10,0.5)
print(arr5)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [14]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
np.random.randint(10,50,5)

array([34, 21, 30, 36, 10])

In [17]:
np.random.randint(3,4,10)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [18]:
arr6=np.random.randint(10,100,15)
print(arr6)

[60 50 64 76 81 62 44 27 13 74 66 93 73 62 79]


In [19]:
np.max(arr6)

93

In [20]:
np.min(arr6)

13

In [21]:
np.mean(arr6)

61.6

In [22]:
np.median(arr6)

64.0